# Generated by Django 5.2.11 on 2026-03-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=15)),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True)),
                ('total_referrals', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
