# Generated by Django 6.0.3 on 2026-03-06 07:56

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_phonepetransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default="India's Smartest Retail ERP", max_length=200)),
                ('hero_title', models.CharField(default='Smart ERP for', max_length=200)),
                ('hero_highlighted_title', models.CharField(default='Indian Retailers', max_length=200)),
                ('hero_subtitle', models.TextField(default='AI-powered billing, inventory & store management — built specifically for Indian retail businesses. Save time, reduce errors, grow faster.')),
                ('hero_highlights', models.CharField(default='GST-Ready Billing,Real-time Inventory,AI-Powered Insights', max_length=500)),
                ('primary_cta_text', models.CharField(default='Book Free Demo', max_length=50)),
                ('secondary_cta_text', models.CharField(default='Watch Demo', max_length=50)),
                ('trusted_retailers_count', models.CharField(default='500+', max_length=50)),
                ('hero_stats_label', models.CharField(default="Today's Sales", max_length=100)),
                ('hero_stats_value', models.CharField(default='₹1,24,500', max_length=50)),
            ],
        ),
    ]
