# Generated by Django 5.2.11 on 2026-03-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_contactsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsubmission',
            name='countryCode',
        ),
    ]
