# Generated by Django 5.2.11 on 2026-03-07 05:48

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_contactsubmission_countrycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('available_to_join', models.IntegerField(blank=True, null=True)),
                ('current_salary', models.CharField(blank=True, max_length=100)),
                ('expected_salary', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
