# Generated by Django 5.2.11 on 2026-03-12 12:00

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_landingpagecontent_cta_badge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, default='About AI-Setu ERP', max_length=255)),
                ('hero_description', models.TextField(blank=True, default='AI-Setu ERP empowers retailers with modern technology to simplify store management. We help SMEs automate operations, improve efficiency, and grow faster with intelligent ERP solutions.')),
                ('about_label', models.CharField(blank=True, default='ABOUT US', max_length=100)),
                ('about_heading', models.CharField(blank=True, default='WE ARE ON A DRIVE TO MAKE THE RETAIL INDUSTRY MORE EFFICIENT.', max_length=255)),
                ('about_description_1', models.TextField(blank=True, default='AI-Setu ERP is the future of retail. From empowering offline stores to managing their inventory and sales with smart technology.')),
                ('about_description_2', models.TextField(blank=True, default='SMEs often struggle to find a comprehensive cloud-based ERP and POS solution that can scale with their growth.')),
                ('about_description_3', models.TextField(blank=True, default='AI-Setu ERP empowers SMEs to use modern ERP tools without complexity and grow their business with automation and analytics.')),
                ('mission_title', models.CharField(blank=True, default='Our Mission', max_length=200)),
                ('mission_description', models.TextField(blank=True, default='Retail businesses are the backbone of the Indian economy, yet many rely on outdated tools. AI-Setu ERP brings modern technology to retail businesses, enabling inventory tracking, billing, sales analytics, and smarter decisions with ease.')),
                ('why_choose_title', models.CharField(blank=True, default='Why Choose AI-Setu ERP?', max_length=200)),
                ('why_point_1', models.CharField(blank=True, default='Smart AI-powered billing', max_length=200)),
                ('why_point_2', models.CharField(blank=True, default='Fast and reliable billing', max_length=200)),
                ('why_point_3', models.CharField(blank=True, default='Real-time inventory tracking', max_length=200)),
                ('why_point_4', models.CharField(blank=True, default='Powerful sales analytics', max_length=200)),
                ('why_point_5', models.CharField(blank=True, default='Built specifically for Indian retailers', max_length=200)),
                ('serve_title', models.CharField(blank=True, default='WHO DO WE SERVE?', max_length=200)),
                ('serve_subtitle', models.CharField(blank=True, default='We serve all types of retail businesses with our ERP solutions.', max_length=255)),
                ('serve1_title', models.CharField(blank=True, default='Kirana Store', max_length=200)),
                ('serve2_title', models.CharField(blank=True, default='General Store', max_length=200)),
                ('serve3_title', models.CharField(blank=True, default='Medical Store', max_length=200)),
                ('serve4_title', models.CharField(blank=True, default='Hardware Store', max_length=200)),
                ('cta_title', models.CharField(blank=True, default='Transform Your Retail Business', max_length=255)),
                ('cta_description', models.TextField(blank=True, default='Join retailers who are already using AI-Setu ERP to streamline operations.')),
                ('cta_button_text', models.CharField(blank=True, default='Book Free Demo', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='available_to_join',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='current_salary',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='expected_salary',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='comparison_subtitle',
            field=models.CharField(default='Discover why retailers are switching to AI-Setu ERP for faster, smarter store management.', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='comparison_title',
            field=models.CharField(default='AI-Setu ERP vs Traditional Software', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='cta_badge',
            field=models.CharField(default='Join 500+ Happy Retailers', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='cta_button_text',
            field=models.CharField(default='Book Free Demo', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='cta_description',
            field=models.TextField(default="Join hundreds of Indian retailers who've switched to smarter billing with AI-Setu ERP. Get started in minutes, no tech skills needed."),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='cta_small_text',
            field=models.CharField(default='No credit card required · Free setup · Cancel anytime', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='cta_title',
            field=models.CharField(default='Ready to Upgrade Your Store?', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='faq1_answer',
            field=models.TextField(default='Yes! AI-Setu ERP is fully GST compliant with automatic tax calculations, GSTIN integration, and GST-ready invoicing.'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='faq1_question',
            field=models.CharField(default='Is it GST Ready?', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='faq2_answer',
            field=models.TextField(default='AI-Setu ERP is cloud-based for the best experience. However, basic billing can work offline and syncs when internet is available.'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='faq2_question',
            field=models.CharField(default='Is Internet Required?', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='faq3_answer',
            field=models.TextField(default='No! Our AI-powered photo detection lets you bill products without barcodes — just snap a photo and the product is identified automatically.'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='faq3_question',
            field=models.CharField(default='Do I need Barcode?', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='faq4_answer',
            field=models.TextField(default='Yes, we provide 24/7 customer support via phone, email, and chat. Our team is always ready to help.'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='faq4_question',
            field=models.CharField(default='Is Support Provided?', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='faq5_answer',
            field=models.TextField(default='Absolutely. We provide complete setup and training for you and your staff as part of the package.'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='faq5_question',
            field=models.CharField(default='Is Training Included?', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='faq6_answer',
            field=models.TextField(default='Annual renewal is available at a competitive rate. Refer others and earn ₹1,000 per renewal incentive!'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='faq6_question',
            field=models.CharField(default='What About Renewal?', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='faq_title',
            field=models.CharField(default='Frequently Asked Questions', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='howitworks_label',
            field=models.CharField(default='Simple Process', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='howitworks_step1_desc',
            field=models.CharField(default='Schedule a quick demo with our team', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='howitworks_step1_title',
            field=models.CharField(default='Book Demo', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='howitworks_step2_desc',
            field=models.CharField(default='We configure everything for you', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='howitworks_step2_title',
            field=models.CharField(default='Setup & Training', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='howitworks_step3_desc',
            field=models.CharField(default='Go live and start selling instantly', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='howitworks_step3_title',
            field=models.CharField(default='Start Smart Billing', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='howitworks_title',
            field=models.CharField(default='How It Works', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='pricing_feature1',
            field=models.CharField(default='Full Access to All Modules', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='pricing_feature2',
            field=models.CharField(default='POS Billing + Inventory', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='pricing_feature3',
            field=models.CharField(default='CRM & Loyalty Programs', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='pricing_feature4',
            field=models.CharField(default='Accounting & Reports', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='pricing_feature5',
            field=models.CharField(default='Employee Management', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='pricing_feature6',
            field=models.CharField(default='Setup & Training Support', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='pricing_feature7',
            field=models.CharField(default='24/7 Customer Support', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='pricing_feature8',
            field=models.CharField(default='AI Photo Billing', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='pricing_label',
            field=models.CharField(default='PRICING', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='pricing_old_price',
            field=models.CharField(default='₹29,999', max_length=50),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='pricing_plan_name',
            field=models.CharField(default='All-Inclusive Package', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='pricing_price',
            field=models.CharField(default='₹12,000', max_length=50),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='pricing_price_suffix',
            field=models.CharField(default='+ GST', max_length=50),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='pricing_title',
            field=models.CharField(default='Simple & Transparent Pricing', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem1_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem1_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem2_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem2_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem3_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem3_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem4_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem4_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem5_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem5_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem_section_label',
            field=models.CharField(default='THE CHALLENGE', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem_section_title',
            field=models.CharField(default='Retailers Face These Daily Problems', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='referral_item1_text',
            field=models.CharField(default='Per Successful Sale', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='referral_item1_value',
            field=models.CharField(default='₹2,000', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='referral_item2_text',
            field=models.CharField(default='Renewal Incentive', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='referral_item2_value',
            field=models.CharField(default='₹1,000', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='referral_item3_text',
            field=models.CharField(default='For Every Successful Referral Purchase', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='referral_item3_value',
            field=models.CharField(default='₹1,000', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='referral_item4_text',
            field=models.CharField(default='Referral Income', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='referral_item4_value',
            field=models.CharField(default='Unlimited', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='referral_label',
            field=models.CharField(default='REFERRAL PROGRAM', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='referral_title',
            field=models.CharField(default='Earn With AI-Setu ERP', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='solution1_desc',
            field=models.TextField(default='Lightning-fast billing with GST compliance'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='solution1_title',
            field=models.CharField(default='POS Billing', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='solution2_desc',
            field=models.TextField(default='Real-time stock tracking & alerts'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='solution2_title',
            field=models.CharField(default='Inventory Management', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='solution3_desc',
            field=models.TextField(default='Customer management & loyalty programs'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='solution3_title',
            field=models.CharField(default='CRM & Loyalty', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='solution4_desc',
            field=models.TextField(default='Automated bookkeeping & reports'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='solution4_title',
            field=models.CharField(default='Accounting', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='solution5_desc',
            field=models.TextField(default='Attendance, payroll & performance'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='solution5_title',
            field=models.CharField(default='Employee Management', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='solution6_desc',
            field=models.TextField(default='Insights at a glance with smart analytics'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='solution6_title',
            field=models.CharField(default='Reports & Dashboard', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='solution_section_label',
            field=models.CharField(default='THE SOLUTION', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='solution_section_title',
            field=models.CharField(default='One Smart ERP For Complete Store Management', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='testimonial1_name',
            field=models.CharField(default='Rajesh Patel', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='testimonial1_role',
            field=models.CharField(default='Kirana Store,Surat', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='testimonial1_text',
            field=models.TextField(default='AI-Setu ERP transformed my billing process. The AI photo detection is a game changer — no more barcode hassles!'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='testimonial2_name',
            field=models.CharField(default='Priya Sharma', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='testimonial2_role',
            field=models.CharField(default='Medical Shop,Surat', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='testimonial2_text',
            field=models.TextField(default='Simple to use and my staff learned it in one day. GST billing is now automatic. Highly recommended!'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='testimonial3_name',
            field=models.CharField(default='Amit Desai', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='testimonial3_role',
            field=models.CharField(default='General Store, Vadodara', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='testimonial3_text',
            field=models.TextField(default='Finally an ERP that understands Indian retail. The pricing is fair and support team is always available.'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='testimonial_label',
            field=models.CharField(default='TESTIMONIALS', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='testimonial_title',
            field=models.CharField(default='What Our Customers Say', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='usp_badge_text',
            field=models.CharField(default='AI-Powered (Beta Feature)', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='usp_description',
            field=models.TextField(default='Our AI technology identifies products from photos — just snap and bill. No barcode scanner needed. Lightning-fast, accurate, and incredibly simple.'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='usp_title',
            field=models.CharField(default='No Barcode? No Problem.', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='who1',
            field=models.CharField(default='Kirana Stores', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='who2',
            field=models.CharField(default='General Stores', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='who3',
            field=models.CharField(default='Medical Shops', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='who4',
            field=models.CharField(default='Hardware Stores', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='who5',
            field=models.CharField(default='Margin Business Retailers', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='who_main_title',
            field=models.CharField(default='Perfect For', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='who_title',
            field=models.CharField(default='Who Is This For?', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.FileField(null=True, upload_to='invoices/'),
        ),
        migrations.AlterField(
            model_name='pricingsignup',
            name='referral_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
