# Generated by Django 5.2.11 on 2026-03-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_aboutpage_alter_jobapplication_available_to_join_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem1_description',
            field=models.TextField(default='Manual billing wastes time & creates long queues'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem1_title',
            field=models.CharField(default='Slow Billing', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem2_description',
            field=models.TextField(default='Inventory mismatches lead to lost sales'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem2_title',
            field=models.CharField(default='No Stock Control', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem3_description',
            field=models.TextField(default="Can't track real profit per product"),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem3_title',
            field=models.CharField(default='Unknown Profit Margin', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem4_description',
            field=models.TextField(default='Business stops when key staff is absent'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem4_title',
            field=models.CharField(default='Staff Dependency', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem5_description',
            field=models.TextField(default='Most Indian products lack barcodes'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='problem5_title',
            field=models.CharField(default='Barcode Not Available', max_length=200),
        ),
    ]
