# Generated by Django 5.2.11 on 2026-03-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_alter_landingpagecontent_problem1_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutPage',
            new_name='AboutPageContent',
        ),
    ]
