# Generated by Django 5.2.11 on 2026-03-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_rename_aboutpage_aboutpagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='feature_title',
            field=models.CharField(default='Features', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='feature_title2',
            field=models.CharField(default='Everything you need to run your retail business smarter.', max_length=100),
        ),
    ]
