# Generated by Django 5.2.11 on 2026-03-13 05:04

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_landingpagecontent_feature_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPageContent',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Build Your Career With AI-Setu 🚀', max_length=255)),
                ('hero_description', models.TextField(default='Join a team building the future of AI-powered ERP systems. Work with innovative people and solve real business problems.')),
                ('culture_title', models.CharField(default='Our Culture', max_length=200)),
                ('culture_1_title', models.CharField(default='Collaboration', max_length=100)),
                ('culture_1_desc', models.TextField(default='We believe teamwork builds better solutions.')),
                ('culture_2_title', models.CharField(default='Innovation', max_length=100)),
                ('culture_2_desc', models.TextField(default='Experiment and create new possibilities.')),
                ('culture_3_title', models.CharField(default='Growth', max_length=100)),
                ('culture_3_desc', models.TextField(default='Continuous learning and career growth.')),
                ('culture_4_title', models.CharField(default='Trust', max_length=100)),
                ('culture_4_desc', models.TextField(default='Transparency and respect always.')),
                ('benefits_title', models.CharField(default='Perks & Benefits', max_length=200)),
                ('benefit_1', models.CharField(default='Flexible Work Culture', max_length=100)),
                ('benefit_2', models.CharField(default='5 Day Work Week', max_length=100)),
                ('benefit_3', models.CharField(default='Learning Budget', max_length=100)),
                ('benefit_4', models.CharField(default='Team Events', max_length=100)),
                ('benefit_5', models.CharField(default='Fast Career Growth', max_length=100)),
                ('benefit_6', models.CharField(default='Friendly Work Environment', max_length=100)),
                ('positions_title', models.CharField(default='Open Positions', max_length=200)),
                ('job_1_role', models.CharField(default='Frontend Developer', max_length=200)),
                ('job_1_details', models.CharField(default='1-3 Years • Ahmedabad', max_length=200)),
                ('job_2_role', models.CharField(default='Backend Developer (Python/Django)', max_length=200)),
                ('job_2_details', models.CharField(default='2-4 Years • Ahmedabad', max_length=200)),
                ('job_3_role', models.CharField(default='AI Engineer', max_length=200)),
                ('job_3_details', models.CharField(default='2+ Years • Remote / Ahmedabad', max_length=200)),
                ('cta_title', models.CharField(default='Ready to Join AI-Setu?', max_length=255)),
                ('cta_description', models.TextField(default='Explore our current openings and apply today.')),
                ('cta_button_text', models.CharField(default='View Openings', max_length=100)),
            ],
        ),
    ]
