# Generated by Django 5.2.11 on 2026-03-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_careerpagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpagecontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
