# Generated by Django 5.2.11 on 2026-03-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_careerpagecontent_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpagecontent',
            name='apply_button_text',
            field=models.CharField(default='Apply For This Job', max_length=100),
        ),
        migrations.AddField(
            model_name='careerpagecontent',
            name='description_heading',
            field=models.CharField(default='Job Description', max_length=100),
        ),
        migrations.AddField(
            model_name='careerpagecontent',
            name='experience_location',
            field=models.CharField(default=('1-4 Years • Remote / Ahmedabad', '2-4 Years • Ahmedabad', '2+ Years • Remote / Ahmedabad'), max_length=255),
        ),
        migrations.AddField(
            model_name='careerpagecontent',
            name='job_description_all_content',
            field=models.TextField(default='• Develop AI powered ERP features.\n• Integrate machine learning models.\n• Work with LLMs and automation.\n• Improve business intelligence systems.\n• Develop modern UI using React.\n• Integrate APIs from backend.\n• Work with UI/UX designers.\n• Improve performance and responsiveness.\n• Develop scalable REST APIs using Django.\n• Work with databases and data models.\n• Collaborate with frontend developers.\n• Optimize backend performance.'),
        ),
        migrations.AddField(
            model_name='careerpagecontent',
            name='job_title',
            field=models.CharField(default='AI Engineer / Frontend / Backend Developer', max_length=255),
        ),
        migrations.AddField(
            model_name='careerpagecontent',
            name='required_skills_all_content',
            field=models.TextField(default='Python, Machine Learning, LLM, TensorFlow, PyTorch, React, JavaScript, Tailwind, HTML, CSS, Django, REST API, PostgreSQL, Docker'),
        ),
        migrations.AddField(
            model_name='careerpagecontent',
            name='skills_heading',
            field=models.CharField(default='Required Skills', max_length=100),
        ),
    ]
