# Generated by Django 5.2.11 on 2026-03-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_careerpagecontent_apply_button_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerpagecontent',
            name='apply_button_text',
        ),
        migrations.RemoveField(
            model_name='careerpagecontent',
            name='description_heading',
        ),
        migrations.RemoveField(
            model_name='careerpagecontent',
            name='experience_location',
        ),
        migrations.RemoveField(
            model_name='careerpagecontent',
            name='job_description_all_content',
        ),
        migrations.RemoveField(
            model_name='careerpagecontent',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='careerpagecontent',
            name='required_skills_all_content',
        ),
        migrations.RemoveField(
            model_name='careerpagecontent',
            name='skills_heading',
        ),
    ]
