# Generated by Django 5.2.11 on 2026-03-13 06:40

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_remove_careerpagecontent_apply_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageContent',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default="Let's Start a Conversation", max_length=200)),
                ('hero_description', models.TextField(default="Ready to transform your business with AI? We're here to help you every step of the way. Reach out and let's build something amazing together.")),
                ('call_title', models.CharField(default='Call Us', max_length=100)),
                ('call_phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('call_subtext', models.CharField(default='Mon–Sat 9:30AM to 6:30PM', max_length=100)),
                ('email_title', models.CharField(default='Email Us', max_length=100)),
                ('email_address', models.EmailField(default='hello@aisetuerp.com', max_length=254)),
                ('email_subtext', models.CharField(default="We'll respond within 24 hours", max_length=100)),
                ('visit_title', models.CharField(default='Visit Us', max_length=100)),
                ('visit_address', models.CharField(default='Surat, India', max_length=255)),
                ('visit_subtext', models.CharField(default='Schedule a meeting', max_length=100)),
                ('support_title', models.CharField(default='Support Hours', max_length=100)),
                ('support_time', models.CharField(default='24/7 Available', max_length=100)),
                ('support_subtext', models.CharField(default='Always here to help', max_length=100)),
                ('form_title', models.CharField(default='Send us a Message', max_length=200)),
                ('name_label', models.CharField(default='Full Name', max_length=100)),
                ('name_placeholder', models.CharField(default='Enter your full name', max_length=200)),
                ('phone_label', models.CharField(default='Phone Number', max_length=100)),
                ('phone_placeholder', models.CharField(default='Enter your phone number', max_length=200)),
                ('email_label', models.CharField(default='Email Address', max_length=100)),
                ('email_placeholder', models.CharField(default='Enter your email address', max_length=200)),
                ('company_label', models.CharField(default='Office Address', max_length=100)),
                ('company_placeholder', models.CharField(default='Enter your office address', max_length=200)),
                ('message_label', models.CharField(default='Message', max_length=100)),
                ('message_placeholder', models.CharField(default='Tell us about your requirements...', max_length=200)),
                ('form_button_text', models.CharField(default='Send Message', max_length=100)),
                ('why_title', models.CharField(default='Why Choose AI-Setu?', max_length=200)),
                ('why_description', models.TextField(default="We're not just another ERP solution. We're your technology partner, committed to transforming your business operations with cutting-edge AI and personalized support.")),
                ('feature_1_title', models.CharField(default='Experienced Team', max_length=100)),
                ('feature_2_title', models.CharField(default='Fast Implementation', max_length=100)),
                ('feature_3_title', models.CharField(default='24/7 Support', max_length=100)),
                ('feature_4_title', models.CharField(default='Quick Response', max_length=100)),
                ('cta_title', models.CharField(default='Ready to Get Started?', max_length=200)),
                ('cta_description', models.TextField(default='Join hundreds of businesses already using AI-Setu to streamline their operations and boost productivity.')),
                ('cta_button_text1', models.CharField(default='Free Consultation', max_length=100)),
                ('cta_button_text2', models.CharField(default='Custom Solutions', max_length=100)),
                ('cta_button_text3', models.CharField(default='24/7 Support', max_length=100)),
            ],
        ),
    ]
