# Generated by Django 5.2.11 on 2026-03-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_contactpagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='pricing_main_desc',
            field=models.CharField(default='Simple, transparent pricing — one package, everything included.', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='pricing_main_title',
            field=models.CharField(default='Pricing', max_length=255),
        ),
    ]
