# Generated by Django 5.2.11 on 2026-03-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_landingpagecontent_pricing_main_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='referral_main_desc',
            field=models.CharField(default='Earn money by referring retailers to AI-Setu ERP.', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='referral_main_title',
            field=models.CharField(default='Referral Program', max_length=255),
        ),
    ]
