# Generated by Django 5.2.11 on 2026-03-14 05:15

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_landingpagecontent_all_reviews_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonFeature',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=255)),
                ('has_ai_setu', models.BooleanField(default=True)),
                ('has_traditional', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
