# Generated by Django 5.2.11 on 2026-03-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_comparisonfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonfeature',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
