# Generated by Django 5.2.11 on 2026-03-14 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_comparisonfeature_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='comparison_feature1',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='comparison_feature2',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='comparison_feature3',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='comparison_feature4',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='comparison_feature5',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='comparison_feature6',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='comparison_feature7',
        ),
    ]
