# Generated by Django 6.0.3 on 2026-03-14 09:35

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0060_remove_landingpagecontent_faq1_answer_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='BlogCategory',
                    fields=[
                        ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100, unique=True)),
                        ('slug', models.SlugField(max_length=100, unique=True)),
                    ],
                    options={
                        'verbose_name_plural': 'Blog Categories',
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='visit_map_url',
            field=models.URLField(blank=True, default='https://goo.gl/maps/example'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='BlogPost',
                    fields=[
                        ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=255)),
                        ('slug', models.SlugField(max_length=255, unique=True)),
                        ('featured_image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                        ('excerpt', models.TextField(help_text='A short summary of the post.')),
                        ('content', models.TextField()),
                        ('author', models.CharField(default='Admin', max_length=100)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('is_published', models.BooleanField(default=False)),
                        ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='website.blogcategory')),
                    ],
                    options={
                        'ordering': ['-created_at'],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
