# Generated by Django 6.0.3 on 2026-03-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0061_blogcategory_contactpagecontent_visit_map_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpagecontent',
            name='call_phone_number',
            field=models.CharField(blank=True, default='+919876543210', max_length=20),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='email_address_link',
            field=models.EmailField(blank=True, default='hello@aisetuerp.com', max_length=254),
        ),
    ]
