# Generated by Django 5.2.11 on 2026-03-17 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0071_page_section_sectionitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPageContent',
        ),
    ]
