# Generated by Django 5.2.11 on 2026-03-17 10:28

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0072_delete_aboutpagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobposition',
            name='job_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='total_positions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='work_place',
            field=models.CharField(default='WFO', max_length=100),
        ),
        migrations.CreateModel(
            name='PolicySection',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='website.policy')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
