# Generated by Django 5.2.11 on 2026-03-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0073_policy_jobposition_job_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allstoretype',
            options={'verbose_name': 'Store Type', 'verbose_name_plural': 'All Store Typesss'},
        ),
    ]
