# Generated by Django 5.2.11 on 2026-03-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0075_alter_allstoretype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['order'], 'verbose_name_plural': 'Challanges'},
        ),
    ]
