# Generated by Django 5.2.11 on 2026-03-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0076_alter_problem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allstoretype',
            options={'verbose_name': 'Store Type', 'verbose_name_plural': 'Demo Form Store Types'},
        ),
        migrations.AlterModelOptions(
            name='storetype',
            options={'ordering': ['order'], 'verbose_name_plural': 'Who Is This For - Store Types'},
        ),
    ]
