# Generated by Django 5.2.11 on 2026-03-17 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0077_alter_allstoretype_options_alter_storetype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['order'], 'verbose_name_plural': 'Challenges'},
        ),
    ]
