# Generated by Django 5.2.11 on 2026-03-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0078_alter_problem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childjobposition',
            options={'verbose_name_plural': 'All Job Positions'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name_plural': 'AboutUs Content'},
        ),
    ]
