# Generated by Django 5.2.11 on 2026-03-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0079_alter_childjobposition_options_alter_page_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='faq_label',
            field=models.CharField(default='FAQ', max_length=255),
        ),
    ]
