# Generated by Django 6.0.3 on 2026-03-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0080_landingpagecontent_faq_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='response_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
