# Generated by Django 5.2.11 on 2026-03-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0084_alter_pricingsignup_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingContent',
            fields=[
            ],
            options={
                'verbose_name': 'Pricing Content',
                'verbose_name_plural': 'Pricing Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.landingpagecontent',),
        ),
    ]
