# Generated by Django 5.2.11 on 2026-03-20 12:58

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0085_pricingcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, default='About AI-Setu ERP', max_length=255)),
                ('hero_description', models.TextField(blank=True, default='AI-Setu ERP empowers retailers with modern technology to simplify store management. We help SMEs automate operations, improve efficiency, and grow faster with intelligent ERP solutions.')),
                ('about_label', models.CharField(blank=True, default='ABOUT US', max_length=100)),
                ('about_heading', models.CharField(blank=True, default='WE ARE ON A DRIVE TO MAKE THE RETAIL INDUSTRY MORE EFFICIENT.', max_length=255)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('about_description_1', models.TextField(blank=True, default='AI-Setu ERP is the future of retail. From empowering offline stores to managing their inventory and sales with smart technology.')),
                ('about_description_2', models.TextField(blank=True, default='SMEs often struggle to find a comprehensive cloud-based ERP and POS solution that can scale with their growth.')),
                ('about_description_3', models.TextField(blank=True, default='AI-Setu ERP empowers SMEs to use modern ERP tools without complexity and grow their business with automation and analytics.')),
                ('mission_title', models.CharField(blank=True, default='Our Mission', max_length=200)),
                ('mission_description', models.TextField(blank=True, default='Retail businesses are the backbone of the Indian economy, yet many rely on outdated tools. AI-Setu ERP brings modern technology to retail businesses, enabling inventory tracking, billing, sales analytics, and smarter decisions with ease.')),
                ('why_choose_title', models.CharField(blank=True, default='Why Choose AI-Setu ERP?', max_length=200)),
                ('why_point_1', models.CharField(blank=True, default='Smart AI-powered billing', max_length=200)),
                ('why_point_2', models.CharField(blank=True, default='Fast and reliable billing', max_length=200)),
                ('why_point_3', models.CharField(blank=True, default='Real-time inventory tracking', max_length=200)),
                ('why_point_4', models.CharField(blank=True, default='Powerful sales analytics', max_length=200)),
                ('why_point_5', models.CharField(blank=True, default='Built specifically for Indian retailers', max_length=200)),
                ('serve_title', models.CharField(blank=True, default='WHO DO WE SERVE?', max_length=200)),
                ('serve_subtitle', models.CharField(blank=True, default='We serve all types of retail businesses with our ERP solutions.', max_length=255)),
                ('cta_title', models.CharField(blank=True, default='Transform Your Retail Business', max_length=255)),
                ('cta_description', models.TextField(blank=True, default='Join retailers who are already using AI-Setu ERP to streamline operations.')),
                ('cta_button_text', models.CharField(blank=True, default='Book Free Demo', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsServeItem',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_serve/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
