# Generated by Django 5.2.11 on 2026-03-21 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0086_aboutpagecontent_aboutusserveitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusserveitem',
            name='about_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serve_items', to='website.aboutpagecontent'),
        ),
        migrations.AlterField(
            model_name='childjobposition',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
