# Generated by Django 5.2.11 on 2026-03-24 05:25

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0089_comparisonfeature_landing_page_faq_landing_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeContent',
            fields=[
            ],
            options={
                'verbose_name': 'Challenge Content',
                'verbose_name_plural': 'Challenge Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.landingpagecontent',),
        ),
        migrations.CreateModel(
            name='ComparisonContent',
            fields=[
            ],
            options={
                'verbose_name': 'Comparison Content',
                'verbose_name_plural': 'Comparison Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.landingpagecontent',),
        ),
        migrations.CreateModel(
            name='FAQContent',
            fields=[
            ],
            options={
                'verbose_name': 'FAQ Content',
                'verbose_name_plural': 'FAQ Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.landingpagecontent',),
        ),
        migrations.CreateModel(
            name='HowItWorksContent',
            fields=[
            ],
            options={
                'verbose_name': 'How It Works Content',
                'verbose_name_plural': 'How It Works Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.landingpagecontent',),
        ),
        migrations.CreateModel(
            name='SolutionContent',
            fields=[
            ],
            options={
                'verbose_name': 'Solution Content',
                'verbose_name_plural': 'Solution Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.landingpagecontent',),
        ),
        migrations.CreateModel(
            name='TestimonialContent',
            fields=[
            ],
            options={
                'verbose_name': 'Testimonial Content',
                'verbose_name_plural': 'Testimonial Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.landingpagecontent',),
        ),
        migrations.CreateModel(
            name='TrustContent',
            fields=[
            ],
            options={
                'verbose_name': 'Trust Strip Content',
                'verbose_name_plural': 'Trust Strip Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.landingpagecontent',),
        ),
        migrations.CreateModel(
            name='USPContent',
            fields=[
            ],
            options={
                'verbose_name': 'USP Content',
                'verbose_name_plural': 'USP Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.landingpagecontent',),
        ),
        migrations.CreateModel(
            name='WhoIsThisForContent',
            fields=[
            ],
            options={
                'verbose_name': 'Who Is This For Content',
                'verbose_name_plural': 'Who Is This For Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.landingpagecontent',),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='available_to_join',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='current_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='TrustItem',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(help_text='lucide-react icon name (shield-check, indian-rupee, cloud, headphones)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('landing_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trust_items', to='website.landingpagecontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
