# Generated by Django 5.2.11 on 2026-03-24 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0090_challengecontent_comparisoncontent_faqcontent_and_more'),
    ]

    operations = [
    ]
