# Generated by Django 5.2.11 on 2026-03-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0091_auto_20260324_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='dummy_field',
            field=models.CharField(default='test', max_length=10),
        ),
    ]
