# Generated by Django 5.2.11 on 2026-03-24 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0092_landingpagecontent_dummy_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='dummy_field',
        ),
    ]
