# Generated by Django 5.2.11 on 2026-03-24 08:49

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0093_remove_landingpagecontent_dummy_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTAContent',
            fields=[
            ],
            options={
                'verbose_name': 'Final CTA Content',
                'verbose_name_plural': 'Final CTA Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.landingpagecontent',),
        ),
        migrations.CreateModel(
            name='HeroContent',
            fields=[
            ],
            options={
                'verbose_name': 'Hero Section Content',
                'verbose_name_plural': 'Hero Section Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.landingpagecontent',),
        ),
        migrations.AlterField(
            model_name='childjobposition',
            name='career_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='website.careerpage'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='career_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_jobs', to='website.careerpage'),
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('landing_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_features', to='website.landingpagecontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
