# Generated by Django 5.2.11 on 2026-03-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0094_ctacontent_herocontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store_types/'),
        ),
    ]
