# Generated by Django 5.2.11 on 2026-03-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0095_adminuser_otp_adminuser_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Meta description for SEO (max 160 chars recommended)', null=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Meta title for SEO (max 70 chars recommended)', max_length=255, null=True),
        ),
    ]
