# Generated by Django 5.2.12 on 2026-03-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0095_adminuser_otp_adminuser_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='show_comparison',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='show_cta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='show_faq',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='show_hero',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='show_how_it_works',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='show_pricing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='show_problem',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='show_referral',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='show_solution',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='show_testimonials',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='show_trust_strip',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='show_usp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='show_who_is_this_for',
            field=models.BooleanField(default=True),
        ),
    ]
