# Generated by Django 5.2.12 on 2026-03-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0096_landingpagecontent_show_comparison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpagecontent',
            name='show_cards',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='show_cta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='show_form',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='show_hero',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='show_why_choose',
            field=models.BooleanField(default=True),
        ),
    ]
