# Generated by Django 5.2.11 on 2026-03-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0096_aboutpagecontent_seo_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCTAContent',
            fields=[
            ],
            options={
                'verbose_name': 'About Us CTA Content',
                'verbose_name_plural': 'About Us CTA Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.aboutpagecontent',),
        ),
        migrations.CreateModel(
            name='AboutHeroContent',
            fields=[
            ],
            options={
                'verbose_name': 'About Hero Content',
                'verbose_name_plural': 'About Hero Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.aboutpagecontent',),
        ),
        migrations.CreateModel(
            name='AboutMissionContent',
            fields=[
            ],
            options={
                'verbose_name': 'Mission & Vision Content',
                'verbose_name_plural': 'Mission & Vision Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.aboutpagecontent',),
        ),
        migrations.CreateModel(
            name='AboutServeContent',
            fields=[
            ],
            options={
                'verbose_name': 'Who We Serve Content',
                'verbose_name_plural': 'Who We Serve Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.aboutpagecontent',),
        ),
        migrations.CreateModel(
            name='AboutStoryContent',
            fields=[
            ],
            options={
                'verbose_name': 'Our Story & Vision',
                'verbose_name_plural': 'Our Story & Vision',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.aboutpagecontent',),
        ),
        migrations.CreateModel(
            name='AboutWhyChooseContent',
            fields=[
            ],
            options={
                'verbose_name': 'Why Choose AI-Setu Content',
                'verbose_name_plural': 'Why Choose AI-Setu Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.aboutpagecontent',),
        ),
    ]
