# Generated by Django 5.2.11 on 2026-03-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0097_aboutctacontent_aboutherocontent_aboutmissioncontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerCTAContent',
            fields=[
            ],
            options={
                'verbose_name': 'Career CTA Content',
                'verbose_name_plural': 'Career CTA Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.careerpage',),
        ),
        migrations.CreateModel(
            name='CareerCultureContent',
            fields=[
            ],
            options={
                'verbose_name': 'Our Culture Content',
                'verbose_name_plural': 'Our Culture Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.careerpage',),
        ),
        migrations.CreateModel(
            name='CareerHeroContent',
            fields=[
            ],
            options={
                'verbose_name': 'Career Hero Content',
                'verbose_name_plural': 'Career Hero Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.careerpage',),
        ),
        migrations.CreateModel(
            name='CareerJobsContent',
            fields=[
            ],
            options={
                'verbose_name': 'Open Positions Content',
                'verbose_name_plural': 'Open Positions Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.careerpage',),
        ),
        migrations.CreateModel(
            name='CareerPerksContent',
            fields=[
            ],
            options={
                'verbose_name': 'Perks & Benefits Content',
                'verbose_name_plural': 'Perks & Benefits Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.careerpage',),
        ),
    ]
