# Generated by Django 5.2.11 on 2026-03-25 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0097_contactpagecontent_show_cards_and_more'),
        ('website', '0098_careerctacontent_careerculturecontent_and_more'),
    ]

    operations = [
    ]
