# Generated by Django 5.2.11 on 2026-03-25 06:44

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0099_merge_20260325_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsWhyChooseItem',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('about_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_items', to='website.aboutpagecontent')),
            ],
            options={
                'verbose_name': 'About Us Why Choose Item',
                'verbose_name_plural': 'About Us Why Choose Items',
                'ordering': ['order'],
            },
        ),
    ]
