# Generated by Django 5.2.11 on 2026-03-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0100_aboutuswhychooseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='childjobposition',
            name='total_positions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='childjobposition',
            name='work_place',
            field=models.CharField(choices=[('WFO', 'WFO'), ('WFH', 'WFH')], default='WFO', max_length=10),
        ),
    ]
