# Generated by Django 5.2.12 on 2026-04-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0107_pricingsignup_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='razorpay_key_id',
            field=models.CharField(blank=True, help_text='The Razorpay Key ID (e.g. rzp_test_...)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='razorpay_key_secret',
            field=models.CharField(blank=True, help_text='The Razorpay Key Secret', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(default='RAZORPAY', max_length=20),
        ),
    ]
