# Generated by Django 5.2.12 on 2026-04-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0108_globalsettings_razorpay_key_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='active_gateway',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('CASHFREE', 'Cashfree')], default='RAZORPAY', help_text='The payment gateway currently in use', max_length=20),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='cashfree_app_id',
            field=models.CharField(blank=True, help_text='The Cashfree App ID (e.g. 56262b...)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='cashfree_environment',
            field=models.CharField(choices=[('SANDBOX', 'Sandbox'), ('PRODUCTION', 'Production')], default='SANDBOX', help_text='Gateway environment', max_length=20),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='cashfree_secret_key',
            field=models.CharField(blank=True, help_text='The Cashfree Secret Key', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('CASHFREE', 'Cashfree')], default='RAZORPAY', max_length=20),
        ),
    ]
