# Generated by Django 5.2.12 on 2026-04-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0109_globalsettings_active_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='base_url',
            field=models.CharField(default='http://localhost:8000', help_text='The full URL of your website (e.g. https://ai-setu.com). Important for payment gateways.', max_length=255),
        ),
    ]
