# Generated by Django 5.2.12 on 2026-04-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0110_globalsettings_base_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='base_url',
        ),
    ]
