# Generated by Django 5.2.11 on 2026-03-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_pricingsignup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leads',
        ),
    ]
