# Generated by Django 6.0.3 on 2026-03-06 04:44

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_demorequest_id_alter_pricingsignup_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonePeTransaction',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_transaction_id', models.CharField(max_length=100, unique=True)),
                ('phonepe_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='PAYMENT_PENDING', max_length=50)),
                ('user_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
