from django.urls import path
from .views import CareerPageAPIView, JobDetailAPIView, PolicyDetailAPIView, PolicyListAPIView, about_page_api, all_store_type, book_demo_api, get_all_testimonials, get_demo_video, get_features, get_footer, get_home_testimonials, get_how_it_works_steps, get_problems, get_referral_perks, get_store_types, get_usp_features,login_view,pricing_signup, landing_page_content_api, submit_contact, apply_job, check_referral, initiate_payment, get_blog_posts, get_blog_post_detail, get_blog_categories, manage_env_api
from . import views 
urlpatterns = [    
    path("api/payment/initiate/", initiate_payment, name="initiate_payment"),
    path("initiate-payment/", initiate_payment, name="initiate_payment_fallback"),
    path("book-demo/", book_demo_api, name="book_demo_api"),
    path('api/login/', login_view, name='login_view'),
    path('pricing-signup/', pricing_signup, name='pricing_signup'),
    path('api/landing-content/', landing_page_content_api, name='landing_page_content_api'),
    path("api/contact/submit/", submit_contact, name="submit_contact"),
    path("apply-job/", apply_job, name="apply_job"),
    path('referral-check/', check_referral, name='check_referral'),
    # path("initiate-payment/", initiate_payment),
    # path("payment-callback/", payment_callback),
    path("razorpay-callback/", views.razorpay_callback, name="razorpay_callback"),
    path("payment-success/", views.payment_success, name="payment_success"),
    path("payment-success/", views.payment_success, name="payment_success"),
    path("api/payment/status/<str:tid>/", views.check_payment_status_api, name="check_payment_status_api"),
    # path("admin/login/", views.admin_login),
    # path("admin/demos/", views.admin_demo_list),
    # path("admin/delete-demo/<int:id>/", views.delete_demo),
    # path("api/about-page/", about_page_content, name="about-page"),
    # path('pages/about/', .as_view(), name='about-page'),
    path('api/pages/about/', about_page_api),
    path("api/career/", CareerPageAPIView.as_view(), name="career-page"),
    path("api/contactus-page/", views.contactus_page_content, name="contactus-page"),
    path("api/problems/", get_problems),
    path("api/features/", get_features),
    path("api/usp-features/", get_usp_features),
    path("api/how-it-works/", get_how_it_works_steps),
    path("api/store-types/", get_store_types),
    path("api/referral-perks/", get_referral_perks),
    path("api/home-testimonials/", get_home_testimonials),
    path("api/testimonials/", get_all_testimonials),
    path("api/blogs/", get_blog_posts, name="get_blog_posts"),
    path("api/blogs/<slug:slug>/", get_blog_post_detail, name="get_blog_post_detail"),
    path("api/blog-categories/", get_blog_categories, name="get_blog_categories"),
    path('api/comparison-features/', views.get_comparison_features, name='comparison-features'),
    path("api/faqs/", views.get_faqs, name="faqs"),
    path("api/login-link/", views.get_login_link, name="login-link"),
    path("api/demo-video/", get_demo_video),
    path("api/all-storetype/", all_store_type, name="all-storetype"),
    path("api/footer/", get_footer),
    path("api/job/<slug:slug>/", JobDetailAPIView.as_view(), name="job-detail"),
    path("api/policies/", PolicyListAPIView.as_view()),
    path("api/policies/<slug:slug>/", PolicyDetailAPIView.as_view()),
    path('api/manage-env/', manage_env_api, name='manage_env_api'),

]